# Alacritty Color Scheme - Dark Theme (TOML format)
# Based on your CSS color variables

[colors.primary]
background = "#1d1e20"  # --theme: rgb(29, 30, 32)
foreground = "#dadadb"  # --primary: rgb(218, 218, 219)
dim_foreground = "#9b9c9d"  # --secondary: rgb(155, 156, 157)
bright_foreground = "#c4c4c5"  # --content: rgb(196, 196, 197)

[colors.cursor]
text = "#1d1e20"
cursor = "#dadadb"

[colors.vi_mode_cursor]
text = "#1d1e20"
cursor = "#9b9c9d"

[colors.search.matches]
foreground = "#1d1e20"
background = "#dadadb"

[colors.search.focused_match]
foreground = "#1d1e20"
background = "#c4c4c5"

[colors.selection]
text = "#dadadb"
background = "#414244"  # --tertiary: rgb(65, 66, 68)

[colors.normal]
black = "#1d1e20"    # background
red = "#e06c75"      # soft red
green = "#98c379"    # soft green
yellow = "#e5c07b"   # soft yellow
blue = "#61afef"     # soft blue
magenta = "#c678dd"  # soft magenta
cyan = "#56b6c2"     # soft cyan
white = "#dadadb"    # primary text

[colors.bright]
black = "#414244"    # tertiary
red = "#ff7b86"      # brighter red
green = "#a9d68a"    # brighter green
yellow = "#f0d18c"   # brighter yellow
blue = "#72c0ff"     # brighter blue
magenta = "#d789e8"  # brighter magenta
cyan = "#67c7d3"     # brighter cyan
white = "#c4c4c5"    # content

[colors.dim]
black = "#2e2e33"    # --entry: rgb(46, 46, 51)
red = "#b85450"
green = "#7a9f60"
yellow = "#b89f62"
blue = "#4e8bc0"
magenta = "#9d60b4"
cyan = "#4692a0"
white = "#9b9c9d"    # secondary

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
background = "#2e2e33"  # --entry
foreground = "#dadadb"

[colors.hints.start]
foreground = "#1d1e20"
background = "#e5c07b"

[colors.hints.end]
foreground = "#1d1e20"
background = "#9b9c9d"
