# Monokai Theme for Alacritty

[colors.primary]
background = '#272822'
foreground = '#f8f8f2'

[colors.normal]
black   = '#272822'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#f4bf75'
blue    = '#66d9ef'
magenta = '#ae81ff'
cyan    = '#a1efe4'
white   = '#f8f8f2'

[colors.bright]
black   = '#75715e'
red     = '#f92672'
green   = '#a6e22e'
yellow  = '#f4bf75'
blue    = '#66d9ef'
magenta = '#ae81ff'
cyan    = '#a1efe4'
white   = '#f9f8f5'

[[colors.indexed_colors]]
index = 16
color = '#fd971f'

[[colors.indexed_colors]]
index = 17
color = '#cc6633'

[[colors.indexed_colors]]
index = 18
color = '#383830'

[[colors.indexed_colors]]
index = 19
color = '#49483e'

[[colors.indexed_colors]]
index = 20
color = '#a59f85'

[[colors.indexed_colors]]
index = 21
color = '#f5f4f1'

[colors.cursor]
text = '#272822'
cursor = '#f8f8f2'

[colors.selection]
text = '#f8f8f2'
background = '#49483e'