# Solarized Dark Theme for Alacritty

[colors.primary]
background = '#002b36'
foreground = '#839496'

[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[[colors.indexed_colors]]
index = 16
color = '#cb4b16'

[[colors.indexed_colors]]
index = 17
color = '#d33682'

[[colors.indexed_colors]]
index = 18
color = '#073642'

[[colors.indexed_colors]]
index = 19
color = '#586e75'

[[colors.indexed_colors]]
index = 20
color = '#657b83'

[[colors.indexed_colors]]
index = 21
color = '#839496'

[colors.cursor]
text = '#002b36'
cursor = '#839496'

[colors.selection]
text = '#839496'
background = '#073642'