# Default backup storage location
backup_root = "assets/backup"

# Window Managers & Desktop Environment
[configs.sway]
source = "$HOME/.config/sway"
dest = "sway"
desc = "Sway window manager configuration"
enabled = true

[configs.waybar]
source = "$HOME/.config/waybar"
dest = "waybar"
desc = "Waybar status bar configuration"
enabled = true

[configs.mako]
source = "$HOME/.config/mako"
dest = "mako"
desc = "Notification"
enabled = true

[configs.swaylock]
source = "$HOME/.config/swaylock"
dest = "swaylock"
desc = "Screen locker configuration"
enabled = true

# Terminals
[configs.kitty]
source = "$HOME/.config/kitty"
dest = "kitty"
desc = "Kitty terminal configuration"
enabled = true

[configs.alacritty]
source = "$HOME/.config/alacritty"
dest = "alacritty"
desc = "Alacritty terminal configuration"
enabled = true

[configs.tmux]
source = "$HOME/.config/tmux"
dest = "tmux"
desc = ""
enabled = true

[configs.bash_dir]
source = "$HOME/.bash/_mixins"
dest = "bash/.bash/_mixins"
desc = ""
enabled = true

[configs.bashrc]
source = "$HOME/.bashrc"
dest = "bash/.bashrc"
desc = ""
enabled = true

[configs.zsh_dir]
source = "$HOME/.zsh/_mixins"
dest = "zsh/.zsh/_mixins"
desc = ""
enabled = true

[configs.zshrc]
source = "$HOME/.zshrc"
dest = "zsh/.zshrc"
desc = ""
enabled = true

# System Configuration
[configs.fontconfig]
source = "$HOME/.config/fontconfig"
dest = "fontconfig"
desc = "Font configuration"
enabled = true

# Development Tools
[configs.nvim]
source = "$HOME/.config/nvim"
dest = "nvim"
desc = "Neovim editor configuration"
enabled = true

# Applications
[configs.rofi]
source = "$HOME/.config/rofi"
dest = "rofi"
desc = "Rofi application launcher configuration"
enabled = true

[configs.mpv]
source = "$HOME/.config/mpv"
dest = "mpv"
desc = "MPV media player configuration"
enabled = true

# System Utilities
[configs.dunst]
source = "$HOME/.config/dunst"
dest = "dunst"
desc = "Dunst notification daemon configuration"
enabled = true

