#!/bin/sh

# Environment setup
source $HOME/.config/river/config/env.sh

# Core configuration
source $HOME/.config/river/config/display.sh
source $HOME/.config/river/config/input.sh
source $HOME/.config/river/config/appearance.sh

source $HOME/.config/river/config/desktop-services.sh
source $HOME/.config/river/config/layout-rivertile.sh
source $HOME/.config/river/config/keybindings.sh
source $HOME/.config/river/config/window-rules.sh

