#!/bin/sh

killall swaybg

# Environment setup
source $HOME/.config/river/modules/env.sh

# Core configuration
source $HOME/.config/river/modules/display.sh
source $HOME/.config/river/modules/input.sh
source $HOME/.config/river/modules/appearance.sh

# Functional modules
source $HOME/.config/river/modules/desktop-services.sh
source $HOME/.config/river/modules/layout.sh
source $HOME/.config/river/modules/keybindings.sh
source $HOME/.config/river/modules/window-rules.sh

